/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicaciontaller;
import javax.swing.JOptionPane;
/**
 *
 * @author hecto
 */
public class VentanaTaller extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaTaller.class.getName());

    /**
     * Creates new form VentanaTaller
     */
    public VentanaTaller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtCostoMano = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        txtDatoExtra = new javax.swing.JTextField();
        btnCostoTotal = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        btnDias = new javax.swing.JButton();
        btnRecursivo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Placa del Vehiculo:");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Propietario:");

        jLabel3.setText("Costo de Mano de Obra:");

        jLabel4.setText("Dias de Reparacion:");

        jLabel5.setText("Valor Extra(Refacciones/Descuento/Ciclos):");

        btnCostoTotal.setText("Calcular Costo Total");
        btnCostoTotal.addActionListener(this::btnCostoTotalActionPerformed);

        btnCrear.setText("Registrar Orden");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnDescuento.setText("Aplicar Descuento");
        btnDescuento.addActionListener(this::btnDescuentoActionPerformed);

        btnDias.setText("Agregar Diaz Plazo");
        btnDias.addActionListener(this::btnDiasActionPerformed);

        btnRecursivo.setText("Preventivo");
        btnRecursivo.addActionListener(this::btnRecursivoActionPerformed);

        jLabel6.setText("Resultado:");
        jLabel6.setName(""); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtResultado.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(74, 74, 74)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCostoMano)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(32, 32, 32)
                            .addComponent(txtDias))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDatoExtra))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnCrear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCostoTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDescuento)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDias)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecursivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCostoMano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCostoTotal)
                    .addComponent(btnDescuento)
                    .addComponent(btnCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDias)
                    .addComponent(btnRecursivo))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private OrdenReparacion orden;
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
        String placa = txtPlaca.getText();
        String prop = txtPropietario.getText();
        double costo = Double.parseDouble(txtCostoMano.getText());
        int dias = Integer.parseInt(txtDias.getText());

        // Instanciación del TDA aplicando constructores y validaciones
        orden = new OrdenReparacion(placa, prop, costo, dias);
        
        jTextArea1.setText("¡Orden de Taller Registrada Correctamente!\n" + 
                orden.getInfoVehiculo() + "\nMano de Obra: $" + orden.getCostoManoDeObra() + 
                " | Días de Reparación: " + orden.getDiasReparacion());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error en los datos: " + ex.getMessage(), 
                "Error de validación", JOptionPane.ERROR_MESSAGE);
    }       
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostoTotalActionPerformed
      if (verificarOrden()) {
        try {
            double refacciones = Double.parseDouble(txtDatoExtra.getText());
            double total = orden.calcularCostoTotalReparacion(refacciones);
            jTextArea1.setText("--- Cálculo de Costo Total ---\n" +
                    "Mano de Obra: $" + orden.getCostoManoDeObra() + "\n" +
                    "Refacciones: $" + refacciones + "\n" +
                    "Costo Total de Reparación: $" + total);
        } catch (Exception ex) {
            jTextArea1.setText("Error: Ingrese un costo de refacciones válido en el campo extra.");
        }
    }
    }//GEN-LAST:event_btnCostoTotalActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        if (verificarOrden()) {
        try {
            double porcentaje = Double.parseDouble(txtDatoExtra.getText());
            orden.aplicarDescuentoTaller(porcentaje);
            jTextArea1.setText("--- Descuento Aplicado ---\n" +
                    "Se aplicó un " + porcentaje + "% de descuento.\n" +
                    "Nuevo Costo de Mano de Obra: $" + String.format("%.2f", orden.getCostoManoDeObra()));
        } catch (Exception ex) {
            jTextArea1.setText("Error: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiasActionPerformed
        if (verificarOrden()) {
        try {
            int diasExtra = Integer.parseInt(txtDatoExtra.getText());
            orden.agregarDiasPlazo(diasExtra);
            jTextArea1.setText("--- Plazo Extendido ---\n" +
                    "Se sumaron " + diasExtra + " días al plazo.\n" +
                    "Nuevo Plazo Total: " + orden.getDiasReparacion() + " días.");
        } catch (Exception ex) {
            jTextArea1.setText("Error: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnDiasActionPerformed

    private void btnRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursivoActionPerformed
        if (verificarOrden()) {
        try {
            int ciclos = Integer.parseInt(txtDatoExtra.getText());
            double costoPreventivo = orden.calcularMantenimientoPreventivoRecursivo(ciclos);
            jTextArea1.setText("--- Mantenimiento Preventivo (Recursivo) ---\n" +
                    "Ciclos proyectados: " + ciclos + "\n" +
                    "Costo Preventivo Acumulado: $" + String.format("%.2f", costoPreventivo));
        } catch (Exception ex) {
            jTextArea1.setText("Error: Ingrese un número entero de ciclos válido en el campo extra.");
        }
    }
    }//GEN-LAST:event_btnRecursivoActionPerformed
    private boolean verificarOrden() {
    if (orden == null) {
        JOptionPane.showMessageDialog(this, "Primero debe registrar la orden de reparación.", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaTaller().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCostoTotal;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnDias;
    private javax.swing.JButton btnRecursivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCostoMano;
    private javax.swing.JTextField txtDatoExtra;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JScrollPane txtResultado;
    // End of variables declaration//GEN-END:variables
}
